# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
    ]
