# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 23:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20180127_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AddField(
            model_name='package',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
