# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20180226_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='service_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
