# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_package_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='path_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
