# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_visit_path_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='special_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
