# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_special_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='upgrade_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='upgrade_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
