# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_auto_20180619_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='upgrade_description',
            field=models.TextField(default=''),
        ),
    ]
