# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_package_upgrade_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='upgraded',
            field=models.BooleanField(default=False),
        ),
    ]
