# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_appointment_upgraded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='upgrade_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='upgrade_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='upgrade_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
