# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_auto_20180628_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
